---
slug: :worldon
depends:
  mikutter: 3.7.0
  plugin:
    - world
    - spell
    - gui
    - gtk
    - photo
    - openimg
    - settings
    - command
    - extract
    - score
    - search
version: '1.0'
author: cobodo
name: Worldon
description: mikutterでMastodonへ接続するworldプラグインです。
